### ISSUE TITLE
Customize Humanization of TimeSpan

### ISSUE THREAD

**Issue by SuperJMN** [Humanizr/Humanizer#1188] opened 2022-03-17 09:43 UTC
I would like that instead of this

- 1 days, 2 hours, 3 minutes

It will produce this

- 1d 2h 3m

That is, to shorten the resulting string. It's for labels in a chart.

Is it possible?

**Comment by neilboyd** [comment] 2022-03-18 06:13
See also #571

**Comment by hazzik** [comment] 2024-02-26 10:17
Duplicate of #571

**Closed by hazzik** 2024-02-26 10:17 UTC
