### ISSUE TITLE
LetterCasing truncates the frensh caracters "é,è..." of a string

### ISSUE THREAD

**Issue by mak5** [Humanizr/Humanizer#563] opened 2016-06-15 09:21 UTC
I used Humanizer to lower case a frensh word "Ajouté" the result was ajout rathar than "ajouté"

**Comment by aloisdg** [comment] 2016-06-15 09:34
@mak5 Hello. Can you add more information and a way to replicate your problem?

**Comment by mak5** [comment] 2016-06-15 09:42
ok, I have an Enum in c# like this:
`public enum ActivityTypes
    {
        Ajouté,
        Modifié,
        Activé,
        Désactivé
    }`

I traied to lower case the value of the enum:
`var type = ActivityTypes.Ajouté.Humanize(LetterCasing.LowerCase)`

I got type = "ajout"

the culter of my asp.net mvc is "fr-FR"

and I reference Humanizer as a projet in my solution (downloaded from github)

**Comment by aloisdg** [comment] 2016-06-15 09:56
> I reference Humanizer as a projet in my solution (downloaded from github)

Which one did you take? Can you try to use NuGet instead.

**Comment by mak5** [comment] 2016-06-15 10:09
I downloaded the zip file of this project "Humanizer-dev" 2 days ago 
the reason why i didn't used NuGet is because it doesn't humanize the TimeSpan with "fr-FR" culture (result always in english)

**Comment by aloisdg** [comment] 2016-06-15 10:25
@mak5 ok. I asked just in case you were using the Core version.

It might be a problem from the lib since 

    string s = ActivityTypes.Ajouté.ToString();
    Console.WriteLine(CultureInfo.CurrentCulture.TextInfo.ToLower(s));

is working great.

**Comment by mak5** [comment] 2016-06-15 10:43
So is it a bug ?

**Comment by aloisdg** [comment] 2016-06-15 12:23
Speaking as a french guy and with my own voice, I would say that to use a french word in a english program is a bug in itself. At least, a huge warning. I guess you have your reasons and after all .NET seems to allow it. 😄 

I think it would be nice if Humanizer handles this kind of fantasy since .NET allows it.

If you want to dig it, clone the project. Look for `EnumUnderTest` and your custom element here. Then, use `EnumHumanizeTests` to test your custom element. 

The problem should come from `EnumHumanizeExtensions` since `ApplyCase()`works as expected:

```C#
ActivityTypes.Ajouté.ToString().ApplyCase (LetterCasing.LowerCase)
```

By the way thank you for your involvement :)

**Comment by hangy** [comment] 2016-06-15 18:17
`EnumHumanizeExtensions` basically calls `ActivityTypes.Ajouté.ToString().Humanize()` in this case, which boils down to the same underlying problem as described in #532.

**Comment by hazzik** [comment] 2016-07-03 22:39
Closing as duplicate of #532.

**Closed by hazzik** 2016-07-03 22:39 UTC
