### ISSUE TITLE
Is the project abandoned?

### ISSUE THREAD

**Issue by ptupitsyn** [Humanizr/Humanizer#1230] opened 2022-10-09 07:10 UTC
No commits since March, PRs are ignored, can anyone please comment on this?

**Comment by 0xced** [comment] 2023-03-03 09:32
I juste stumbled on #1219 (which is a duplicate of #1154) and saw that it's already fixed by #1178 in the main branch. Unfortunately a new package that includes this fix was never released on NuGet. 😟

@clairernovotny Is this project looking for a new maintainer? Any comment would be appreciated. 🙏

**Comment by JDA88** [comment] 2023-03-06 17:47
I was about to start using the library, but I do not want to invest on an abandoned project, any status would be appreciated indeed :)

**Comment by Hefaistos68** [comment] 2023-05-11 12:23
With the last changes made in January 2022 it seems there is not much going on lately.

**Comment by stefannikolei** [comment] 2023-10-24 17:27
I started a fork of this project to keep it alive, cause there is no reaction from any maintainer since a year. 

What I changed is, the targetframeworks. I only target .net6. 

Also I had trouble publishing a package for each language  so there is only one package with all languages. 

The fork is over at https://github.com/Lingualizr/Lingualizr

**Comment by SimonCropp** [comment] 2024-02-20 10:43
Project has been rebooted

**Closed by SimonCropp** 2024-02-20 10:43 UTC

**Comment by SimonCropp** [comment] 2024-02-20 11:17
@0xced yes. hopefully doing a v3 beta1 in the next few days
