### ISSUE TITLE
Localization Issue with DateTime and TimeSpan Humanizer

### ISSUE THREAD

**Issue by AndreiaFileno** [Humanizr/Humanizer#380] opened 2015-02-10 10:01 UTC
Hi, thank you for this awesome library! Found it recently and it's just what I needed to improve a few applications I've been working on.

Seeing that this library supports .NET 4+ and Silverlight 5, I opened up a new Silverlight Application in order to test it and see how it works and ran into a few issues. When humanizing a datetime or a timespan, the current UI culture is not picked up, meaning that, even I that I have the current UI culture set to "pt-BR", it will display its content in English (the default, I've assumed). Forcing the current UI culture or any other culture doesn't seem to work either:
string now = DateTime.UtcNow.AddHours(5).Humanize();
string now = DateTime.UtcNow.AddHours(5).Humanize(true, null, CultureInfo.CurrentUICulture);
string now = DateTime.UtcNow.AddHours(5).Humanize(true, null, new CultureInfo("fr-BE"));
In all three scenarios it displays "5 hours from now".

I checked other extensions such as ToWords() and ToOrdinalWords() and everything works as expected - the following:
string days = DateTime.DaysInMonth(2015, 10).ToWords(GrammaticalGender.Masculine);
string days2 = DateTime.DaysInMonth(2015, 10).ToOrdinalWords(GrammaticalGender.Feminine);
- correclty displays, "trinta e um" and "trigésima primeira".

I tested it using the most recent nuget release (1.33.7) but also tried it with an older version (1.31.0) and I can still reproduce the same issues. (Also opened up a new WPF application but there I can't reproduce anything, everything works as expected.)

Any thoughts?
Thanks.

**Comment by MehdiK** [comment] 2015-02-11 07:54
Thanks for reporting this @AndreiaFileno. I honestly have no idea about Silverlight and its potential issues but I don know that the localisations work on other platforms just fine! I will keep this here as a bug hoping someone can shed some light on it for you.

**Comment by AndreiaFileno** [comment] 2015-02-11 16:45
Thank you @MehdiK . 
Since localisation is working just fine in some extensions and the issues only occur on specific ones, I thought it was worth posting it here.

**Comment by MehdiK** [comment] 2015-02-12 07:39
That's a fair point. Although I can't see how these extensions work on other platforms and only fails on SL, it could still be a bug.

**Comment by lazarofl** [comment] 2015-08-07 03:21
I'm using the version `1.37.7` and I have the same issue.

```c#
using Humanizer;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Globalization;

namespace SharedKernelTests.Extensions
{
    [TestClass]
    public class DataHumanizadaTests
    {

        [TestMethod]
        [Description("Ontem")]
        public void Ontem()
        {
            //expected "ontem" but the result value is "yesterday"
            Assert.AreEqual(
                "ontem",
                DateTime.UtcNow.AddDays(-1).Humanize(culture: new CultureInfo("pt-BR")));
        }

    }
}
```

I've tried to change CultureInfo to `ru-RU`, `es-ES` and etc., but all of them are resulting in an english version.

**Comment by MehdiK** [comment] 2015-08-13 07:45
Thanks for reporting the issue @lazarofl. Can you please verify what happens when you set the culture like this:

            Thread.CurrentThread.CurrentCulture = new CultureInfo("ru-RU");
            Thread.CurrentThread.CurrentUICulture = new CultureInfo("ru-RU");

**Comment by onovotny** [comment] 2015-10-25 21:05
Is this still an issue? Is it limited to Silverlight?

**Comment by gabrielrainha** [comment] 2015-11-13 18:06
Just reproduced the issue in Universal Windows Platform too, using pt-BR.
Every method failed to return localized strings but ToWords, ToOrdinalWords and Ordinalize.
I tried setting the culture on the app manifest, by using .Globalization.ApplicationLanguages.PrimaryLanguageOverride and by explicitly passing CultureInfo to Humanize method.

**Comment by onovotny** [comment] 2015-11-13 18:46
If you could share the UnitTests, that would be helpful.

**Comment by gabrielrainha** [comment] 2015-11-19 17:43
I created a Unit Test App for Universal Windows, configured the UnitTest manifest default language do pt-BR and added a reference to the last stable version of Humanizer through NuGet. 
All tests fail but the last three, as shown in the test result window below the code.

```c#
[TestClass]
public class HumanizerTests
{
    private CultureInfo _culture = new CultureInfo("pt-BR");

    [TestMethod]
    public void Humanize_DateTime_ReturnsLocalized()
    {
        DateTime date = DateTime.Now.AddDays(-1);
        string text = date.Humanize(culture: _culture);
        Assert.AreEqual("ontem", text);
    }

    [TestMethod]
    public void Humanize_Timespan_ReturnsLocalized()
    {
        TimeSpan time = 1.Seconds();
        string text = time.Humanize(culture: _culture);
        Assert.AreEqual("1 segundo", text);
    }

    [TestMethod]
    public void Pluralize_String_ReturnsLocalized()
    {
        string singularText = "Homem";
        string text = singularText.Pluralize();
        Assert.AreEqual("Homens", text);
    }

    [TestMethod]
    public void Singularize_String_ReturnsLocalized()
    {
        string pluralText = "Homens";
        string text = pluralText.Singularize();
        Assert.AreEqual("Homem", text);
    }

    [TestMethod]
    public void ToQuantity_Integer_ReturnsLocalized()
    {
        string singularText = "homem";
        string text = singularText.ToQuantity(2);
        Assert.AreEqual("2 homens", text);
    }

    [TestMethod]
    public void ToOrdinal_Integer_ReturnsLocalized()
    {
        int number = 2;
        string text = number.Ordinalize(GrammaticalGender.Masculine);
        Assert.AreEqual("2º", text);
    }

    [TestMethod]
    public void ToOrdinalWords_Integer_ReturnsLocalized()
    {
        int number = 2;
        string text = number.ToOrdinalWords(GrammaticalGender.Masculine, _culture);
        Assert.AreEqual("segundo", text);
    }

    [TestMethod]
    public void ToWords_Integer_ReturnsLocalized()
    {
        int number = 2;
        string text = number.ToWords(GrammaticalGender.Masculine, _culture);
        Assert.AreEqual("dois", text);
    }
}
```
![image](https://cloud.githubusercontent.com/assets/11670858/11278716/9b504c1a-8ed3-11e5-9588-235dfb5141ff.png)

**Comment by mexx** [comment] 2015-11-20 07:00
I think it have to do how the resources are retrieved, as we only have `pt` resources.
It could be a bug in Silverlight's and UWP's implementation of `ResourceManager`.

**Comment by onovotny** [comment] 2015-11-23 20:49
I've isolated this into a repro project for tracking. I've removed the tests that rely on the ambient thread culture and just left the explicit calls as it's likely the same underlying issue.

[LocalizationOnUwp.zip.docx](https://github.com/Humanizr/Humanizer/files/42018/LocalizationOnUwp.zip.docx)
Rename to `.zip`

The repro shows the same tests passing with .net 4.6.

**Comment by gabrielrainha** [comment] 2015-11-24 17:51
Funny thing: just forked the whole solution and cloned it locally, then I created a UWP UnitTest project, added a reference to the Humanizer project and added that same good old Unit Test I used previously.
All tests passed.

Just a note: I replaced all instances of "Homem", which follows a plural rule that is not yet supported, for another string I knew would work ("Segundo", to be precise). I'll work on that plural rule later on.

**Comment by gabrielrainha** [comment] 2015-11-26 13:41
Another discovery:
If I add a reference to Humanizer through Nuget, it does not work. But if I remove that reference and add a direct reference to the dll downloaded from Nuget via "Add Reference > Browse", it does work.

**Comment by marcoscheel** [comment] 2015-12-07 13:55
Just to another ME TOO. I'm developing in VS2015 Update 1 a UWP (Desktop+Phone) app. I support en-US and de-DE. For my date related usage of Humanizer I only get en-US ressources. Using NUGET to reference your superb code. Any ETA about looking/fixing the bug?

**Comment by onovotny** [comment] 2015-12-07 14:39
An update here...this is a bug with the UWP build targets that Microsoft is looking into. The bug affects using any NuGet package with satellite resources in it. Microsoft has a repro and should get back to me soon with an update.

**Comment by b0bben** [comment] 2016-06-23 12:18
Any news on the fix from MS side?

Thx.

**Comment by syedhassaanahmed** [comment] 2016-09-15 07:43
A shame this still doesn't work. @onovotny did MS get back to you with an update?

Thanks

**Comment by xleon** [comment] 2017-03-23 14:16
Same here on asp.net core application and "es-ES", Humanizer.Core.es 2.1.0 installed.

    Thread.CurrentThread.CurrentCulture = new CultureInfo("es-ES");
    timeSpan.Humanize(2); // produces english results
    timeSpan.Humanize(2, new CultureInfo("es-ES"); // // produces english results

**Comment by Paul-Brenner-Tangoe** [comment] 2018-02-01 15:40
@onovotny do you have a link to the Microsoft bug report? This is still broken

**Comment by onovotny** [comment] 2018-02-01 15:54
I just re-ran my repro in VS 2017 and it was ok:

**Comment by onovotny** [comment] 2018-02-01 15:56
What version of VS are you using and what project format? I am using VS 2017 15.5 targeting Creators Update. It changed the old `project.json` to `PackageReference`.

**Comment by J-F-B-M** [comment] 2018-02-01 16:00
Currently also stumbling over this.

VS 2015 Ultimate 14.0.25431.01 Update 3

With NuGet: DateTime doesnt localize, as described. Rest works.
With downloaded and referenced DLL: Works as expected.

Problem is I can only add one Resources-DLL as direct reference, as they are all named the same (or I don't understand references correctly, which is entirely possible).
I want to support multiple languages in the near future, so the workaround works *now*.

**Comment by onovotny** [comment] 2018-02-01 16:01
@J-F-B-M what kind of project is that for? UWP?

**Comment by J-F-B-M** [comment] 2018-02-01 16:05
Ultimately a .NET Web Application.
We have multiple Projects which compile to Class Libraries. The affected Library is a dependency of the WebApp and is a "Class Library"-Project.

**Comment by Paul-Brenner-Tangoe** [comment] 2018-02-01 16:07
VS 2017 15.5.4. I'm using Humanize 2.2 in a Xamarin project with a PCL. I'm having the same problem as J-F-B-M, I don't understand how to apply the work around because then I'd need to reference multiple Humanize dll's with the same name.

**Comment by onovotny** [comment] 2018-02-01 16:08
Does your web app have a reference to Humanizer as well?

**Comment by onovotny** [comment] 2018-02-01 16:09
@Paul-Brenner-Tangoe you should not reference the dll's by name, they wont' go in to the right directory.

Did you also add a nuget reference to Humanizer from your head projects? Using `PackageReference` and .NET Standard class libraries fixes a lot of common issues.

**Comment by onovotny** [comment] 2018-02-01 16:09
I'm closing this as external since the core issue was fixed. Please file new issues with specific issues.

**Closed by onovotny** 2018-02-01 16:09 UTC
Labels: bug, external

**Comment by J-F-B-M** [comment] 2018-02-01 16:11
Yes, that was NuGet all along. I'm seeing this trouble in Unit-Tests and from C#-Interactive (initialized with the affected Project). This should, in my understanding, bypass the WebApp-Project.

**Comment by onovotny** [comment] 2018-02-01 16:16
@J-F-B-M there were a lot of bugs fixed since VS 2015. I would strongly suggest trying on VS 2017 and seeing if they're just fixed for you there.

**Comment by Paul-Brenner-Tangoe** [comment] 2018-02-01 16:30
@onovotny Thanks for the quick replies and help. Apologies for wasting your time, installing it into my Xamarin.iOS and Xamarin.Droid projects as well as the PCL fixed it.

**Comment by onovotny** [comment] 2018-02-01 16:46
@Paul-Brenner-Tangoe no worries, it's a common shortfall of packages.config. I would recommend moving over to `PackageReference` as you no longer need to do that anymore with that.

**Comment by xalikoutis** [comment] 2018-04-11 14:49
Same problem here, Xamarin Forms project i have added several locale assemblies as
Humanizer.Core.de
Humanizer.Core.es
Humanizer.Core.sv

everytime i call
`((DateTime) value).Humanize(utcDate:false, culture: new CultureInfo("es-ES"));`

i get english
like `3 minutes ago`

XF .net standard PackageReference

**Comment by vackup** [comment] 2018-05-10 04:48
Yep, same problem here in a Xamarin.Forms app, calling Humanizer from the Core (.net Standard project)

I'm using Humanizer.Core.es 2.2.0 package for Spanish
And calling it 

`fecha.Humanize(culture: new CultureInfo("es-AR")); // fecha is a DateTime`

And getting results in English, "N days ago" eg

**Comment by cassionandi** [comment] 2018-09-25 14:12
Any workarounds for this?

**Comment by souchprod** [comment] 2020-02-21 09:55
So, does it mean that Humanizer is dead / working only in English ?
This issue is closed but absolutely not resolved, and no workaround.
After 5 years...

**Comment by EmmanuelJego** [comment] 2020-06-09 13:43
Same here!

**Comment by cemrich** [comment] 2020-06-15 07:42
This seems to be a Xamarin build issue (for Android at least), not a Humanizer one - see https://github.com/xamarin/xamarin-android/issues/2012. I think this issue should be mentioned in the readme file, because Xamarin support for Humaizer is not complete as long as this issue exists. 

I ran into the missing translations after being well into my project and now have difficulty to deal with the fallout. Especially as there seems to be no workaround for this issue. Stating the restrictions (English only for Xamarin on Android) could save a lot of users from a lot of trouble.

**Comment by patrinks** [comment] 2020-06-26 20:41
Same here.
On Xamarin Forms for iOS it works fine, but on Android it doesn't. String always in english.
I will have to remove the library from the project. 😢

**Comment by cemrich** [comment] 2020-06-27 18:55
I worked around this issue by referencing the Humanizer dlls directly from my head projects and the shared project. I placed the dlls inside a separate project directory with following structure:

```
Humanizer.dll
de/Humanizer.resources.dll
```

I have not yet tested this solution for more than one localization package.

**Comment by patrinks** [comment] 2020-06-29 12:54
> I worked around this issue by referencing the Humanizer dlls directly from my head projects and the shared project. I placed the dlls inside a separate project directory with following structure:
> 
> ```
> Humanizer.dll
> de/Humanizer.resources.dll
> ```
> 
> I have not yet tested this solution for more than one localization package.

@cemrich, did this work on a Xamarin Forms project?

**Comment by cemrich** [comment] 2020-06-29 18:18
> @cemrich, did this work on a Xamarin Forms project?

This works for a Xamarin.Forms 4.6 project with Android and iOS heads.

**Comment by KevinAnass** [comment] 2021-02-19 11:40
> > @cemrich, did this work on a Xamarin Forms project?
> 
> This works for a Xamarin.Forms 4.6 project with Android and iOS heads.

how you do that ?

**Comment by Polyariz** [comment] 2021-02-26 14:23
There is the workaround solution for Xamarin Forms:
[](https://stackoverflow.com/questions/66387512/humanizer-localization-issue-in-xamarin-forms/66387513#66387513)

**Comment by felipechavez** [comment] 2021-04-12 21:23
> There is the workaround solution for Xamarin Forms:
> https://stackoverflow.com/questions/66387512/humanizer-localization-issue-in-xamarin-forms/66387513#66387513

I confirm that workaround works with the lastest stable Xamarin Forms version. I testes with es-ES

**Comment by joaofx** [comment] 2021-12-23 23:38
Hello!

I was getting the problem described in this issue.

What solved for me is to reference Humanizer in my entry project. In my case is a web application, so I had to add at my Web.csproj. Probably if you are using other type of project, like Windows Forms, you have to add into your executable project.

When building the project, msbuild will copy the localized files to the output path.

If Humanizer is referenced in a class library that your entry project depends, it won't copy the localized files.

Good luck!
