### ISSUE TITLE
Vocabularies.AddPaucal is missing

### ISSUE THREAD

**Issue by emejibka** [Humanizr/Humanizer#948] opened 2020-06-08 06:16 UTC
Hello.

I try to use ToQuantity method with russian language. How i can use it if number end with 2 or 3 or 4 ?
```c#
Vocabularies.Default.AddSingular("день", "день");
Vocabularies.Default.AddPlural("день", "дня");
//Vocabularies.Default.AddPaucal("день", "дня"); - missing method
"день".ToQuantity(i);
```

@hazzik can you help?

**Comment by hazzik** [comment] 2020-07-09 10:34
@emejibka unfortunately only English is supported for inflections.

**Comment by Jarek300** [comment] 2021-01-24 11:49
Yes, we need support for 'paucal'. I haven't known that this language feature has a name. 

For example, in polish, you say 'one **minute** - jedna **minuta**', 'five **minutes** - pięć **minut**', but 'two **minutes** - dwie **minuty**'.  

Humanizer returns "dwie **minut**"  for 'two minutes' what is incorrect.

https://en.wikipedia.org/wiki/Grammatical_number#Paucal

**Comment by hazzik** [comment] 2024-02-27 23:43
@Jarek300 I've created a separate issue.

**Comment by hazzik** [comment] 2024-02-27 23:44
Sort of duplicate of #689

**Closed by hazzik** 2024-02-27 23:44 UTC

**Comment by vadysa** [comment] 2025-04-08 13:09
@hazzik  I saw that currently only English is supported for inflections, which is understandable. But I was wondering — would it be possible to add support for custom inflection rules and user-defined vocabularies?

That way, even if full multi-language support isn’t feasible out of the box, the community could at least define and share inflection rules for their own languages (like Russian, for example). It would really help make the library more flexible and useful internationally.

For example:
```
count switch
    {
        1 => word,
        int n when n % 10 >= 2 && n % 10 <= 4 && (n % 100 < 10 || n % 100 >= 20) => word+"а",
        _ => word + "ов"
    };
```

What do you think?
