### ISSUE TITLE
CultureNotFoundException MalteseFormatter

### ISSUE THREAD

**Issue by jswigart** [Humanizr/Humanizer#1260] opened 2023-03-24 13:12 UTC
![image](https://user-images.githubusercontent.com/4065267/227529350-10637813-a503-449c-b515-deb457ecbd1a.png)

In the formatter registry

https://github.com/Humanizr/Humanizer/blob/main/src/Humanizer/Configuration/FormatterRegistry.cs

There is a RegisterDefaultFormatter function that catches and ignores exceptions with the comment 
 // Some OS's may not support the particular culture. Not much we can do for those.
 
 Why then are the calls to register with a custom formatter not protected in the same way with their own exception catcher, when their associated culture may also similarly not be supported on a particular OS?
 
 This seems like a clear oversight, and one I am running into when attempting to run a dotnet app on steam deck via it's proton emulation. I am already bundling ICU with the application, as per
 
 https://learn.microsoft.com/en-us/dotnet/core/extensions/globalization-icu

**Comment by jswigart** [comment] 2023-03-25 22:33
For example. Do this
<img width="723" alt="image" src="https://user-images.githubusercontent.com/4065267/227745471-45268f1d-4b86-46e5-b87c-c92903a3e30a.png">

**Comment by jswigart** [comment] 2023-03-25 23:12
Here's an example 
<img width="521" alt="image" src="https://user-images.githubusercontent.com/4065267/227746720-6b2b5d50-4858-46fc-9294-f06b0f7f646c.png">

the actual constructor of the formatter needs to be wrapped in the try/catch, as that is where it may fail. using a delegate to do that in this case

**Comment by hazzik** [comment] 2024-02-27 04:09
Duplicate of #1126

**Closed by hazzik** 2024-02-27 04:09 UTC
