### ISSUE TITLE
Add option to convert numbers to different words depending on context

### ISSUE THREAD

**Issue by ahjota** [Humanizr/Humanizer#496] opened 2015-12-11 01:17 UTC
So I was thinking of adding a Korean localization for ToWords() and ToOrdinalWords(), but am having difficulty with the way numbers are handled in Korean in general.

There are two numbering systems, the Korean system and the Chinese system. The Chinese system (1, 2, 3 => 일, 이, 삼) is used for counting money, in dates, and for large quantities. The Korean system (1, 2, 3, => 하나, 둘, 셋) is generally used for counting small quantities. There are other rules that I exclude for brevity, but you get the idea. It's really confusing.

I can't see a way given the current API to register a NumberToWordsConverter that can handle this. Does it make sense to extend the API and overload ToWords() so that it accepts a "context" argument?

var minutesLeft = "15";
minutesLeft.ToWords(Context.Time);

Other ideas would be grand. This is also an issue for other languages, such as Tagalog (which uses Tagalog numbers as well as Spanish-derived numbers).

**Comment by hazzik** [comment] 2017-05-12 00:25
We can infer the time & date contexts as we have the extensions for these entities. 
The "large vs small" numbers probably can be dealt as well without specifying the context. 
The only thing which we do not have from above is money. The problem is - how many other contexts do exist? What are the "other rules that I exclude for brevity"? 

It might be worth to implement in a separate "Humanizer.Korean" namespace if you can generalize the rules and other people do agree with these rules. Otherwise, it shall be implemented in a client code.

I'm going to close the issue, as there was not much attention given. Feel free to submit the PR.

**Closed by hazzik** 2017-05-12 00:25 UTC
Labels: localisation
