### ISSUE TITLE
Error en Spanish

### ISSUE THREAD

**Issue by cesaracosta8014** [Humanizr/Humanizer#1002] opened 2020-11-02 22:43 UTC
"radiadores".Singularize() => radiadore not exist in spanish correct "radiador"

"Carburadores".Singularize() => carburadore not exist in spanis correct "carburador"

**Comment by hazzik** [comment] 2020-11-03 00:11
Singularize/Pluralize only support English.

Duplicate of #891

**Closed by hazzik** 2020-11-03 00:11 UTC
