### ISSUE TITLE
Satelite language packages are not getting copied into the bin

### ISSUE THREAD

**Issue by rothschild86** [Humanizr/Humanizer#784] opened 2019-02-05 09:29 UTC
Hi there,

Out of ideas here. Here's my test:

Installed packages:
```
  <package id="Humanizer.Core" version="2.5.16" targetFramework="net471" />
  <package id="Humanizer.Core.de" version="2.5.16" targetFramework="net471" />
  <package id="Humanizer.Core.fr" version="2.5.16" targetFramework="net471" />
  <package id="Humanizer.Core.ru" version="2.5.16" targetFramework="net471" />
  <package id="Humanizer.Core.zh-CN" version="2.5.16" targetFramework="net471" />
```

Test:
```
var cultures = new string[] { "en", "fr", "de", "ru", "zh-CN" };
var result = string.Join("<br>", cultures.Select(x => $"{x}: {TimeSpan.FromDays(dayCount).Humanize(culture: new CultureInfo(x))}"));
```

Output for (23 days):
```
en: 3 weeks
fr: 3 weeks
de: 3 weeks
ru: 3 недели //the only one that actually got localized
zh-CN: 3 weeks
```

How should I go about troubleshooting this?

Assuming it's an issue of missing dlls, what process is responsible for copying them into bin?

 Thank you.

**Comment by onovotny** [comment] 2019-03-04 23:41
That should be all handled by VS. That said, you shouldn't be using `packages.config` anymore as that has a lot of issues... 

In the latest VS 2017 versions, you should be able to right-click that file and select "migrate to PackageReference" (and do that on each project that has one).

**Comment by rothschild86** [comment] 2019-03-05 07:20
I'm locked into VS 2015 and .net standard. Perhaps that configuration hasn't been tested in a while and is not working quite right.

**Comment by onovotny** [comment] 2019-03-05 10:45
NuGet satellite packages are an old feature and have worked for a long time. I'd suggest filing an issue on the NuGet repo (https://github.com/nuget/home/issues) since whatever the issue is would be on their end.

**Comment by SimonCropp** [comment] 2024-02-17 23:03
closing this since it is a bug in VS

**Closed by SimonCropp** 2024-02-17 23:03 UTC
