### ISSUE TITLE
Release build for Device failing on Windows Phone 8.1 WinRT

### ISSUE THREAD

**Issue by camilomartinez** [Humanizr/Humanizer#428] opened 2015-06-15 15:29 UTC
I am facing an issue while building a WP 8.1 WinRT application using Humanizer. It only happens when using Release configuration for an actual device not an emulator. The build error I receive is

```
Error : DEP6810 : MdilXapCompile.exe failed with error code 1004.
See log file '...\obj\Release\MDIL\MDILXapCompileLog.txt' for more details.
```

The only useful line in that log contains:

```
Error: Compile filter argument specified non-existent file:
...\obj\Release\MSIL\af\Humanizer.resources.dll
Invalid argument
```

which points out to an issue with resources in Humanizer. The error seems to be similar to one mention in this other app issue [(RateMyApp Issue #45)](http://github.com) which makes me think it might be related with using resources from a PCL.

Are you aware of this issue? Anyone else facing it?

**Comment by MehdiK** [comment] 2015-06-21 00:58
Thanks for reporting the issue @camilomartinez. This is the first time I'm seeing this error. You're right. It seems to be the same issue reported [here](https://github.com/Microsoft/rate-my-app/issues/45). The suggested solution sounds a bit strange. I will see what can be done.

**Comment by PombeirP** [comment] 2015-08-07 08:11
FWIW, I'm also facing this issue. I'm compiling Debug for an actual device.

**Comment by MehdiK** [comment] 2015-08-17 11:10
Thanks for reporting @PombeirP.

**Comment by PombeirP** [comment] 2015-09-08 12:56
Hi @MehdiK. Any news on a fix for this issue?

**Comment by MehdiK** [comment] 2015-09-11 07:22
Haven't had the chance to look further into this @PombeirP.

**Comment by PombeirP** [comment] 2015-09-11 07:43
No problem. In the meantime, I've had to remove Humanizer from our app in order to contain the crashes seen in the wild. WP can be a difficult beast :-(

**Comment by onovotny** [comment] 2015-11-18 01:29
So couple of thoughts here...

1. What version of VS is this; I assume 2013 Update 5? Is it any different with VS 2015? Do you have a consistent repro? 

I'd like to get to the bottom of this. There's an open PR, #469, to split the locale's out into satellite packages but I'm not sure if that'll really fix the issue.

If there's a way to get a repro, I can dive deeper and raise the issue with the appropriate teams at Microsoft as well.

**Comment by austhomp** [comment] 2015-11-19 16:57
The issue is actually due to the fact that MS changed how they handle resources between Windows Phone 8 and 8.1 and Universal apps. WP 8.0 and below use .resx files like we're used to, and the newer things use .resw files. Here is a [nice description of the change](http://www.jayway.com/2014/04/22/windows-phone-8-1-for-developers-localizing-apps/).

Here is a [MSDN Blog post about the issue](http://blogs.msdn.com/b/philliphoff/archive/2014/11/19/missingmanifestresourceexception-when-using-portable-class-libraries-in-winrt.aspx) and ways to work around it.

From my understanding of the proposed solution, if we know what resources are in the PCL we can load them via reflection and inject them into the main resource system. The consumers would need to do this, or maybe a separate nuget package could be provided that did that automatically. The advantage there is that the nuget can be kept in sync with any additional resource files added to Humanizer.

**Comment by onovotny** [comment] 2015-11-19 18:54
I can confirm this bug and have a repro here (rename to zip)
[LocalizationRepro.zip.docx](https://github.com/Humanizr/Humanizer/files/39342/LocalizationRepro.zip.docx)

Interestingly, this bug only seems to occur on VS 2013; it works fine in VS 2015. I suspect the packaging tooling (even for Win Phone 8.1 projects) changed a bit.

To be clear, this appears a tooling bug. PCL's can definitely continue to have ResX files and use the ResourceManager as those are supported in the PCL surface area.

Can you try opening/building/deploying your code in VS 2015?

**Comment by SimonCropp** [comment] 2024-02-17 22:37
closing since Windows Phone  is dead

**Closed by SimonCropp** 2024-02-17 22:37 UTC
Labels: bug, external
