### ISSUE TITLE
DateHumanize_MultipleHoursAgo in polish

### ISSUE THREAD

**Issue by jemunk** [Humanizr/Humanizer#830] opened 2019-06-15 06:23 UTC
In version 2.6.2

For one user we are getting a System.ArgumentException: The resource object with key 'DateHumanize_MultipleHoursAgo' was not found Parameter name: resourceKey
The user is having his UI set to Polish

**Comment by AKTheKnight** [comment] 2019-06-20 20:30
Hi @jemunk,

It seems there is a value for MultipleHoursAgo in the polish translations:
https://github.com/Humanizr/Humanizer/blob/23c4c2a526deb0f101b39fe060fca66f5e66c823/src/Humanizer/Properties/Resources.pl.resx#L135-L137

Any chance you could show the code you are using?

**Comment by peppy** [comment] 2019-08-23 04:29
Also a duplicate of #690.

**Comment by Filipowicz251** [comment] 2020-07-18 14:32
I have stil the same bug after one year. I've included Humanizer.Core and Humanizer.Core.Pl as a nuget for my Android version - but it is throwing this error all the time...

**Comment by praksis-jw** [comment] 2021-09-24 13:16
We are experiencing the same issue in xamarin forms. Only Android - IOS works fine. Is there any possible way to fix this?

**Comment by KSemenenko** [comment] 2021-10-01 19:48
any updates?

**Comment by KSemenenko** [comment] 2021-10-01 19:50
I have the same issue for some languages on Andoird, iOS works fine

**Comment by daflotsch** [comment] 2022-03-01 14:48
We have the same issue on WPF (as dotNet 6) with Polish language: The resource object with key 'DateHumanize_MultipleHoursAgo' was not found (Parameter 'resourceKey')
Any chance this can be fixed? Thank you

**Comment by hazzik** [comment] 2024-02-22 00:35
Duplicate of #690

**Closed by hazzik** 2024-02-22 00:35 UTC
