### ISSUE TITLE
ToQuantity for other localizations

### ISSUE THREAD

**Issue by TheDeaX-Lab** [Humanizr/Humanizer#892] opened 2019-12-29 14:18 UTC
Hello, can you say something about the progress on this?  The report was published back in February 2018 and was answered after 1.5 years only in March 2019 ...
https://github.com/Humanizr/Humanizer/issues/689

**Comment by hazzik** [comment] 2024-02-27 04:58
Duplicate of #689

**Closed by hazzik** 2024-02-27 04:58 UTC
