### ISSUE TITLE
Titleize is removing accented characters in Core.pt 2.0.1

### ISSUE THREAD

**Issue by rubenslopes** [Humanizr/Humanizer#572] opened 2016-07-01 14:26 UTC
Hi,

this happens,
 
`Console.WriteLine("rubens armôa lopes".Titleize()); //Rubens Arm A Lopes`

while the expected is,

` Console.WriteLine("rubens armôa lopes".Titleize()); //Rubens Armôa Lopes`

Thank you for create and maintain such a great library

**Comment by hazzik** [comment] 2016-07-03 22:37
Closed as duplicate of #532.

**Closed by hazzik** 2016-07-03 22:37 UTC
Labels: duplicate
