### ISSUE TITLE
CultureNotFoundException ("ku") on Windows / .NET 4.7.2

### ISSUE THREAD

**Issue by TimSirmovics** [Humanizr/Humanizer#1064] opened 2021-05-03 23:10 UTC
After updating to 2.9.9 we are getting the following exception.

```
System.TypeInitializationException: The type initializer for 'Humanizer.Configuration.Configurator' threw an exception. ---> System.Globalization.CultureNotFoundException: Culture is not supported.
Parameter name: name
ku is an invalid culture identifier.
   at System.Globalization.CultureInfo..ctor(String name, Boolean useUserOverride)
   at Humanizer.Configuration.FormatterRegistry..ctor() in /_/src/Humanizer/Configuration/FormatterRegistry.cs:line 24
   at Humanizer.Configuration.Configurator..cctor() in /_/src/Humanizer/Configuration/Configurator.cs:line 28
   --- End of inner exception stack trace ---
   at Humanizer.Configuration.Configurator.get_CollectionFormatters() in /_/src/Humanizer/Configuration/Configurator.cs:line 25
   at Humanizer.CollectionHumanizeExtensions.Humanize[T](IEnumerable`1 collection) in /_/src/Humanizer/CollectionHumanizeExtensions.cs:line 19
```

**Comment by hangy** [comment] 2021-05-04 06:06
If you're on Win 7, Xamarin, or iOS, this is probably a duplicate of https://github.com/Humanizr/Humanizer/issues/1059#issuecomment-830841807.

**Closed** 2021-05-05 13:34 UTC
