### ISSUE TITLE
The resource object with key 'DateHumanize_MultipleDaysFromNow' was not found Parameter name: resourceKey

### ISSUE THREAD

**Issue by pvdberge** [Humanizr/Humanizer#1194] opened 2022-04-19 08:35 UTC
An exception is thrown when using the 'hr' culture.
`The resource object with key 'DateHumanize_MultipleDaysFromNow' was not found Parameter name: resourceKey`
```
System.ArgumentException:
   at Humanizer.Localisation.Formatters.DefaultFormatter.Format (Humanizer, Version=2.14.0.0, Culture=neutral, PublicKeyToken=979442b78dfc278e: /_/src/Humanizer/Localisation/Formatters/DefaultFormatter.cs:137)
   at Humanizer.Localisation.Formatters.DefaultFormatter.DateHumanize (Humanizer, Version=2.14.0.0, Culture=neutral, PublicKeyToken=979442b78dfc278e: /_/src/Humanizer/Localisation/Formatters/DefaultFormatter.cs:49)
   at Humanizer.DateTimeHumanizeStrategy.DateTimeHumanizeAlgorithms.DefaultHumanize (Humanizer, Version=2.14.0.0, Culture=neutral, PublicKeyToken=979442b78dfc278e: /_/src/Humanizer/DateTimeHumanizeStrategy/DateTimeHumanizeAlgorithms.cs:216)
   at Humanizer.DateTimeHumanizeStrategy.DateTimeHumanizeAlgorithms.DefaultHumanize (Humanizer, Version=2.14.0.0, Culture=neutral, PublicKeyToken=979442b78dfc278e: /_/src/Humanizer/DateTimeHumanizeStrategy/DateTimeHumanizeAlgorithms.cs:141)
   at Humanizer.DateTimeHumanizeStrategy.DefaultDateTimeHumanizeStrategy.Humanize (Humanizer, Version=2.14.0.0, Culture=neutral, PublicKeyToken=979442b78dfc278e: /_/src/Humanizer/DateTimeHumanizeStrategy/DefaultDateTimeHumanizeStrategy.cs:16)
   at Humanizer.DateHumanizeExtensions.Humanize (Humanizer, Version=2.14.0.0, Culture=neutral, PublicKeyToken=979442b78dfc278e: /_/src/Humanizer/DateHumanizeExtensions.cs:24)
```

I found a similar issue that was fixed a few months ago: #1170

**Comment by hazzik** [comment] 2024-02-22 00:34
Duplicate of #690

**Closed by hazzik** 2024-02-22 00:34 UTC
