### ISSUE TITLE
Missing resource TimeSpanHumanize_MultipleSeconds in Polish?

### ISSUE THREAD

**Issue by SirSparkles** [Humanizr/Humanizer#776] opened 2019-01-17 00:02 UTC
Hi,

Just got the following error reported from a user. Unfortunately am not sure exactly which locale it is, but the user is Polish:

`System.ArgumentException: The resource object with key 'TimeSpanHumanize_MultipleSeconds' was not found  Nazwa parametru: resourceKey     
w Humanizer.Localisation.Formatters.DefaultFormatter.Format(String resourceKey, Int32 number, Boolean toWords)     
w Humanizer.TimeSpanHumanizeExtensions.CreateTheTimePartsWithUpperAndLowerLimits(TimeSpan timespan, CultureInfo culture, TimeUnit maxUnit, TimeUnit minUnit, Boolean toWords)     
w TVRename.ChooseFile..ctor(FileInfo left, FileInfo right) `

The line of code that is producing the issue is: `10000.Seconds().Humanize(2);`

Thanks

**Comment by MarkSummerville** [comment] 2019-01-22 00:34
Seems to be missing in the Resources.fi-FI.resx resources file

**Comment by KSemenenko** [comment] 2019-01-24 15:02
The sameException for ru-RU

**Comment by peppy** [comment] 2019-08-23 04:31
Another instance of #690, related to xamarin (android?) not including satellite dependencies properly. Would be great if this didn't cause exceptions to be thrown.

**Comment by matibak** [comment] 2020-03-23 15:53
Still a problem

**Comment by Filipowicz251** [comment] 2020-07-18 14:43
Exactly, problem still occurs.

**Comment by BieleckiLtd** [comment] 2021-09-15 13:28
Repro steps:
```
var test = DateTime.UtcNow - TimeSpan.FromSeconds(2);
Debug.Print(test.Humanize()); // OK
Debug.Print(test.Humanize(culture: new CultureInfo("pl-PL"))); // FAILS
```

**Comment by amis92** [comment] 2022-10-14 22:15
I have found out why that happens.

The error is sadly a bit misleading. Consider these code excerpts:

https://github.com/Humanizr/Humanizer/blob/606e958cb83afc9be5b36716ac40d4daa9fa73a7/src/Humanizer/Localisation/Formatters/DefaultFormatter.cs#L131-L138

https://github.com/Humanizr/Humanizer/blob/606e958cb83afc9be5b36716ac40d4daa9fa73a7/src/Humanizer/Localisation/Formatters/CzechSlovakPolishFormatter.cs#L5-L20

So, the actual missing resource keys *are* missing, they just show up invalid in the exception text. The missing ones are those with `_Paucal` suffix - there are no such resource keys.

Generally, I'd say that it's a global issue. English (fallback) resources don't contain special, culture-specific-suffix additions. I have not come up with a good, quick fix for this. We'd probably need to somehow detect the fallback is used and retry with an unsuffixed resource key.

**Comment by hazzik** [comment] 2024-02-22 00:32
Duplicate of #690

**Closed by hazzik** 2024-02-22 00:32 UTC
Labels: bug
