### ISSUE TITLE
Is there a way to "dehumanize" human readable date like "Tomorrow" to a dateTime?

### ISSUE THREAD

**Issue by saroup** [Humanizr/Humanizer#861] opened 2019-10-04 17:04 UTC
It would very useful to have something that takes in things like 
"Tomorrow"
"In 2 weeks"
"Next Month"
"Yesterday" 
and turns it into a DateTime Object

**Comment by erikvojtko** [comment] 2019-10-08 08:22
Hi, can I work on this Issue?

**Comment by hazzik** [comment] 2019-11-05 08:47
Duplicate of #691

**Closed by hazzik** 2019-11-05 08:47 UTC

**Comment by hazzik** [comment] 2019-11-05 08:48
In short. There is no built in way to do this. Here is a future request #691 and older closed issue #112.
