### ISSUE TITLE
The resource object with key 'DateHumanize_MultipleYearsAgo' was not found

### ISSUE THREAD

**Issue by bradleyuk** [Humanizr/Humanizer#814] opened 2019-04-25 13:06 UTC
Exception "The resource object with key 'DateHumanize_MultipleYearsAgo' was not found" thrown when browser (chrome) language set to **Czech**

Have tried with Humanizer.Core.cs v2.6.2 installed and just with Humanizer.Core, Happens both times.

`[ArgumentException: The resource object with key 'DateHumanize_MultipleYearsAgo' was not found
Parameter name: resourceKey]
   Humanizer.Localisation.Formatters.DefaultFormatter.Format(String resourceKey, Int32 number, Boolean toWords) +432
   Humanizer.Localisation.Formatters.DefaultFormatter.DateHumanize(TimeUnit timeUnit, Tense timeUnitTense, Int32 unit) +52
   Humanizer.DateTimeHumanizeStrategy.DateTimeHumanizeAlgorithms.DefaultHumanize(DateTime input, DateTime comparisonBase, CultureInfo culture) +1135
   Humanizer.DateTimeHumanizeStrategy.DefaultDateTimeHumanizeStrategy.Humanize(DateTime input, DateTime comparisonBase, CultureInfo culture) +18
   Humanizer.DateHumanizeExtensions.Humanize(DateTime input, Boolean utcDate, Nullable`1 dateToCompareAgainst, CultureInfo culture) +155
   Humanizer.DateHumanizeExtensions.Humanize(Nullable`1 input, Boolean utcDate, Nullable`1 dateToCompareAgainst, CultureInfo culture) +73`

**Comment by AKTheKnight** [comment] 2019-04-27 14:07
Hi @bradleyuk It looks like we don't have a translation for that yet, would you be able to help with missing translations in Czech? If so let me know and I'll find what other things we are missing.

**Comment by bradleyuk** [comment] 2019-05-01 20:55
Sure, let me know which Czech translations you need.

But surely it should gracefully fallback to default/English rather than
throw an exception?

**Comment by AKTheKnight** [comment] 2019-06-20 20:37
Okay, so I'm really confused now, looking in the source we do have a value, for this:
https://github.com/Humanizr/Humanizer/blob/23c4c2a526deb0f101b39fe060fca66f5e66c823/src/Humanizer/Properties/Resources.cs.resx#L153-L155

@bradleyuk Are you still able to reproduce this issue? And if so any chance I could see the code you're running?

**Comment by astro75** [comment] 2019-08-01 07:52
I had a similar problem, we use only english version (Humanizer.Core) but the clients PC had a different system language that caused the exception. I would be really nice if it defaulted to english if other languages are not installed

**Comment by peppy** [comment] 2019-08-23 04:28
Same issue as #690. Still affecting us.

**Comment by bradleyuk** [comment] 2019-10-01 10:20
Still occurring, also for "DateHumanize_MultipleMonthsFromNow" in Czech... :(

**Comment by Filipowicz251** [comment] 2020-07-18 14:42
The same exception for over a Year. I suppose nobody will fix it :)

**Comment by dolejska-daniel** [comment] 2023-11-30 07:50
Hi, had a similar problem. The issue is due to the fact that you only have `Humanizer.Core` installed. This package does not contain translations for other languages. Either install `Humanizer.Core.Cs` (if you need only Czech) or the whole `Humanizer` package (in case you need more languages).

We were using WASM and currently do not need translations, so we stick with `Humanizer.Core` only and use this to force English localization and solve the issue (from `Program.cs` before building the WASM host):
```csharp
CultureInfo.DefaultThreadCurrentCulture = new CultureInfo("en-US");
CultureInfo.DefaultThreadCurrentUICulture = new CultureInfo("en-US");
```

**Comment by hazzik** [comment] 2024-02-22 00:34
Duplicate of #690

**Closed by hazzik** 2024-02-22 00:34 UTC
