### ISSUE TITLE
CS0455 Error while using Humanizer Extension Methods in view files

### ISSUE THREAD

**Issue by okankocyigit** [Humanizr/Humanizer#625] opened 2017-04-11 08:25 UTC
I've a simply code in my index.cshtml,

```
<div>
    @10.Seconds().Humanize()
</div>
```

Then I'm getting this error ,

> Type parameter ''TTargetEnum' inherits conflicting constraints 'System.ValueType' and 'System.IComparable'

**Comment by MaStr11** [comment] 2017-05-08 14:13
I can't reproduce this bug. I tried creating a new ASP.NET Core App and added the line above. This gave me `"10" is not valid at the start of a code block. Only identifiers, keywords, comments, "(" and "{" are valid.` However `@(10.Seconds().Humanize())` worked as expected.

I tested this with 
```
C:\Program Files\dotnet>dotnet.exe --info
.NET Command Line Tools (1.0.3)

Product Information:
 Version:            1.0.3
 Commit SHA-1 hash:  37224c9917

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.3
```

and the latest dev-branch of Humanizer. @okankocyigit can you give some more context (asp.net version used. Humanizer version used?)

**Comment by maxdobeck** [comment] 2017-05-12 03:21
@MaStr11 did you use  
`@10.Seconds().Humanize()` 
or 
`@(10.Seconds().Humanize())` 
for your tests.  Could it be the difference in parenthesis?

**Comment by MaStr11** [comment] 2017-05-12 04:50
`@10.Seconds().Humanize()` gave a syntax error while  `@(10.Seconds().Humanize())` worked as expected. The  error mentioned originally was not reproducable.

**Comment by SimonCropp** [comment] 2024-02-20 10:07
Closing since this is not a problem with humanizer

**Closed by SimonCropp** 2024-02-20 10:07 UTC
